# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # keycloak
  - releases/keycloak/keycloak-realm.yaml
  - releases/keycloak/keycloak.yaml
