# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # namespaces
  - releases/ns-keycloak.yaml

  # keycloak
  - releases/keycloak.yaml
