# Ordered list of releases.

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # kube-ingress
  - releases/kube-ingress/cert-manager.yaml
  - releases/kube-ingress/external-dns.yaml
  - releases/kube-ingress/nginx-ingress.yaml
  - releases/kube-ingress/nginx-ingress-internal.yaml
