# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # monitor
  # - releases/monitor/prometheus.yaml
  # - releases/monitor/prometheus-adapter.yaml
  - releases/monitor/prometheus-operator.yaml
  - releases/monitor/grafana.yaml
  - releases/monitor/fluentd-elasticsearch.yaml
