# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # etcd
  - releases/etcd/0-etcd.yaml
  - releases/etcd/etcd.yaml
