# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # namespaces
  - releases/ns-monitor.yaml

  # monitor
  - releases/prometheus.yaml
  - releases/prometheus-adapter.yaml
  - releases/grafana.yaml
