# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # vault
  - releases/vault/consul.yaml
  - releases/vault/vault.yaml
