# Ordered list of releases.

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: elastic
    url: https://helm.elastic.co
  - name: kiwigrid
    url: https://kiwigrid.github.io

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # elastic
  - releases/elastic/elasticsearch.yaml
  - releases/elastic/kibana.yaml
  - releases/elastic/fluentd-elasticsearch.yaml
