# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # argo
  - releases/argo.yaml
  - releases/argo-cd.yaml
  # - releases/argo-events.yaml
  - releases/argo-rollouts.yaml
