# Ordered list of releases.

repositories:
  - name: codecentric
    url: https://codecentric.github.io/helm-charts

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # keycloak
  - releases/keycloak/keycloak.yaml
