# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # consul
  - releases/consul/0-consul.yaml
  - releases/consul/consul.yaml
