# Ordered list of releases.

helmfiles:
  # kube-ingress
  - releases/kube-ingress/cert-manager.yaml
  - releases/kube-ingress/nginx-ingress.yaml

  # kube-system
  - releases/kube-system/kube2iam.yaml
  - releases/kube-system/metrics-server.yaml
  - releases/kube-system/kube-state-metrics.yaml
  # - releases/kube-system/cluster-autoscaler.yaml
  # - releases/kube-system/cluster-overprovisioner.yaml
  # - releases/kube-system/efs-provisioner.yaml

  # monitor
  - releases/monitor/prometheus.yaml
  - releases/monitor/prometheus-adapter.yaml
  - releases/monitor/grafana.yaml
