# Ordered list of releases.

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: harbor
    url: https://helm.goharbor.io
  - name: oteemocharts
    url: https://oteemo.github.io/charts
  - name: codecentric
    url: https://codecentric.github.io/helm-charts

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # kube-system
  - releases/kube-system/kube2iam.yaml
  - releases/kube-system/metrics-server.yaml
  # - releases/kube-system/kube-state-metrics.yaml
  - releases/kube-system/cluster-autoscaler.yaml
  - releases/kube-system/cluster-overprovisioner.yaml
  - releases/kube-system/k8s-spot-termination-handler.yaml
  - releases/kube-system/efs-provisioner.yaml

  # monitor
  # - releases/monitor/prometheus.yaml
  # - releases/monitor/prometheus-adapter.yaml
  - releases/monitor/prometheus-operator.yaml
  - releases/monitor/grafana.yaml

  # kube-ingress
  - releases/kube-ingress/cert-manager.yaml
  - releases/kube-ingress/external-dns.yaml
  - releases/kube-ingress/nginx-ingress.yaml

  # keycloak
  - releases/keycloak/keycloak.yaml

  # argo
  - releases/argo/argo.yaml
  - releases/argo/argo-cd.yaml
  - releases/argo/argo-rollouts.yaml
  # - releases/argo/argo-events.yaml

  # devops
  - releases/devops/chartmuseum.yaml
  - releases/devops/docker-registry.yaml
  - releases/devops/jenkins.yaml
  - releases/devops/sonatype-nexus.yaml
  - releases/devops/sonarqube.yaml
  # - releases/devops/harbor.yaml
