# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # elastic
  - releases/elastic/elasticsearch.yaml
  - releases/elastic/kibana.yaml
  - releases/elastic/fluentd-elasticsearch.yaml
