# Ordered list of releases.

environments:
  default:
    values:
      - environments/default.yaml
  eks-demo:
    values:
      - environments/eks-demo.yaml

helmfiles:
  # devops
  - releases/chartmuseum.yaml
  - releases/docker-registry.yaml
  # - releases/harbor.yaml
  - releases/jenkins.yaml
  # - releases/sonarqube.yaml
  # - releases/sonatype-nexus.yaml
