repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: prometheus-operator
    namespace: monitor
    chart: stable/prometheus-operator
    version: ~8.12.10
    installed: true
    # wait: true
    values:
      - prometheus-operator.yaml.gotmpl
