# common
cluster:
  name: default

aws:
  region: ap-northeast-2

# kube-ingress
cert-manager:
  issuer-email: me@nalbam.com

nginx-ingress:
  controller:
    kind: DaemonSet

# kube-system
cluster-autoscaler:
  iam-role: default-autoscaling

efs-provisioner:
  iam-role: default-efs

# monitor
grafana:
  # username: admin
  # password: password
  domain: grafana.demo.mzdev.be

prometheus:
  domain: prometheus.demo.mzdev.be

# argo
argo:
  domain: argo.demo.mzdev.be
  bucket: default-argo
  iam-role: default-argo

argo-cd:
  username: admin
  # password: "$(htpasswd -nbBC 10 '' 'password' | tr -d ':\n' | sed 's/$2y/$2a/')"
  password: "$2a$10$RihNM/bmql87aKhSa/U0DOmTx5JDPl2byap07bLSNRtsEXFiq87E2"
  domain: argocd.demo.mzdev.be

# keycloak
keycloak:
  username: admin
  password: password
  domain: keycloak.demo.mzdev.be
