repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: chartmuseum
    namespace: devops
    chart: stable/chartmuseum
    version: ~2.11.0
    installed: true
    # wait: true
    values:
      - chartmuseum.yaml.gotmpl
