repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: docker-registry
    namespace: devops
    chart: stable/docker-registry
    version: ~1.8.3
    installed: true
    # wait: true
    values:
      - docker-registry.yaml.gotmpl
