repositories:
  - name: oteemocharts
    url: https://oteemo.github.io/charts

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: sonarqube
    namespace: devops
    chart: oteemocharts/sonarqube
    version: ~6.2.0
    installed: true
    # wait: true
    values:
      - sonarqube.yaml.gotmpl
