repositories:
  - name: oteemocharts
    url: https://oteemo.github.io/charts

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: sonatype-nexus
    namespace: devops
    chart: oteemocharts/sonatype-nexus
    version: ~2.0.0
    installed: true
    # wait: true
    values:
      - sonatype-nexus.yaml.gotmpl
