repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: sonatype-nexus
    namespace: devops
    chart: stable/sonatype-nexus
    version: ~1.23.1
    installed: true
    # wait: true
    values:
      - sonatype-nexus.yaml.gotmpl
