repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: ns-argo-cd
    namespace: default
    chart: incubator/raw
    version: ~0.2.3
    installed: true
    wait: true
    # force: true
    values:
      - resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: argo-cd

  - name: argocd
    namespace: argo-cd
    chart: argo/argo-cd
    version: ~2.0.3
    installed: true
    # wait: true
    values:
      - argo-cd.yaml.gotmpl
