repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

environments:
  default:
    values:
      - ../../environments/default.yaml
  eks-demo:
    values:
      - ../../environments/eks-demo.yaml

releases:
  - name: ns-argo-rollouts
    namespace: default
    chart: incubator/raw
    version: ~0.2.3
    installed: true
    wait: true
    # force: true
    values:
      - resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: argo-rollouts

  - name: argo-rollouts
    namespace: argo-rollouts
    chart: incubator/raw
    version: ~0.2.3
    installed: true
    # wait: true
    force: true
    recreatePods: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "/bin/sh"
        args:
          - -c
          - kubectl apply -n argo-rollouts -f https://raw.githubusercontent.com/argoproj/argo-rollouts/stable/manifests/install.yaml
    values:
      - argo-rollouts.yaml.gotmpl
