repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

environments:
  default:
    values:
      - ../environments/default.yaml
  eks-demo:
    values:
      - ../environments/eks-demo.yaml

releases:
  - name: prometheus
    namespace: monitor
    chart: stable/prometheus
    version: ~10.4.0
    installed: true
    # wait: true
    values:
      - ../values/prometheus.yaml.gotmpl
