repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: prometheus
    namespace: monitor
    chart: stable/prometheus
    version: "9.5.1"
    installed: '{{ env "PROMETHEUS_INSTALLED" | default "false" }}'
    wait: true
    values:
      - nameOverride: prometheus

        kubeStateMetrics:
          ## If false, kube-state-metrics will not be installed
          ##
          enabled: false
