repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: prometheus
    namespace: monitor
    chart: stable/prometheus
    version: "9.7.2"
    installed: true
    wait: true
    values:
      - nameOverride: prometheus

        server:
          enabled: true
          persistentVolume:
            enabled: false

        alertmanager:
          enabled: false
          persistentVolume:
            enabled: false

        kubeStateMetrics:
          enabled: false
