repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: prometheus
    namespace: monitor
    chart: stable/prometheus
    version: "9.5.2"
    installed: true
    wait: true
    values:
      - nameOverride: prometheus

        kubeStateMetrics:
          enabled: false
